### PR TITLE
Changed name of field application to subject and fixed relevant views…

### LINKED ISSUE #51: Accept both subject and redirect URL as query params for Feedback
If we arrive at the feedback app with the following query string:

/?redirect=www.google.com/fdsafjiosasfd&subject=Google

It should reference "Google" as the topic for feedback, and should redirect to `www.google.com/fdsafjiosasfd` when the user clicks "Done" after submitting feedback.

Why should we use `subject` and not `application`? `Dispatch` and `Certification` are both parts of the `Caseflow` application, but we want to segment feedback on those two experiences. Using a more generic name will be less confusing later on if we want to further segment feedback (say, if we wanted to collect feedback on Step 2 of Dispatch specifically)

We should also change the DB column name and the model to `subject` from application.

### PR DESCRIPTION
**Pull request by nemodjuric**
… and tests.
caseflowfeedback 2
caseflowfeedback 3
caseflowfeedback 4

To test - make sure 'Caseflow' instead of Certification shows on all Submitting Feedback pages. For admin view - make sure submitted feedback shows as with 'Caseflow' subject you submitted. 
rake db:migrate
rake db:test:prepare (for rspec)

fixes #51

### CODE REVIEW

File: app/controllers/feedback_controller.rb [hunk 1]
```diff
@@ -9,6 +9,7 @@ def admin
 
   def new
     @feedback = Feedback.new
+    session[:subject] = params[:subject] || "Dispatch"
```
Comment (amprokop) [inline app/controllers/feedback_controller.rb]: We should default to just "Caseflow", I think— why did we change this to "Dispatch"?

Comment (amprokop) [inline app/controllers/feedback_controller.rb]: The reason is that "Caseflow" is the name of the whole ecosystem we're building. It's the most generic name for the thing we're working on. Dispatch is one piece of the Caseflow ecosystem. I wouldn't assume that all feedback is for Dispatch, but it all should be about Caseflow.

**Review by amprokop — CHANGES_REQUESTED** [review]
Change the naming, then let's merge this!

File: app/controllers/feedback_controller.rb (hunk 1 above)
Comment (nemodjuric) [inline app/controllers/feedback_controller.rb]: I assumed that concept around subject was to refer to one piece of the Caseflow system, that's why 'Dispatch' was put, as one subsystem.

**Review by amprokop — APPROVED** [review]

**Comment by amprokop** [comment]
LGTM
